spring.application.name=fintime

spring.datasource.url=jdbc:postgresql://localhost:5432/fintime
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


logging.level.org.springframework=DEBUG
logging.level.com.fintime.fintime=DEBUG
